var licenses =
[
    [ "Third-party libraries", "licenses.html#tpl_licenses", [
      [ "1. The Charm++ Parallel Programming System", "licenses.html#charm_license", null ],
      [ "2. The Parsing Expression Grammar Template Library", "licenses.html#pegtl_license", null ],
      [ "3. C++ Template Unit Test Framework", "licenses.html#tut_license", null ],
      [ "4. Boost C++ libraries", "licenses.html#boost_license", null ],
      [ "5. Cartesian product, a Boost MPL algorithm", "licenses.html#cartesian_product_license", null ],
      [ "6. The HDF5 data model", "licenses.html#hdf5_license", null ],
      [ "7. The NetCDF data model", "licenses.html#netcdf_license", null ],
      [ "8. ExodusII for storing data for finite element analyses", "licenses.html#exodusii_license", null ],
      [ "9. Zoltan for static load balancing", "licenses.html#zoltan_license", null ],
      [ "10. RNGSSELIB for random number generation", "licenses.html#rngsselib_license", null ],
      [ "11. TestU01 for statistical testing of random number generators", "licenses.html#testu01_license", null ],
      [ "12. PStreams for POSIX process Control", "licenses.html#pstreams_license", null ],
      [ "13. Hypre for linear solvers and preconditioners", "licenses.html#hypre_license", null ],
      [ "14. Libstdc++ for standard C++ containers and algorithms", "licenses.html#libstdcpp_license", null ],
      [ "15. Libc++ for standard C++ containers and algorithms", "licenses.html#libcpp_license", null ],
      [ "16. OpenMPI for the message passing interface", "licenses.html#openmpi_license", null ],
      [ "17. Intel Math Kernel Library for BLAS/LAPACK and random number generation", "licenses.html#mkl_license", null ],
      [ "18. PugiXML for XML format reading and writing", "licenses.html#pugixml_license", null ]
    ] ],
    [ "Compilers", "licenses.html#compiler_web", [
      [ "1. Clang C++ compiler", "licenses.html#clang_web", null ],
      [ "2. GNU C++ compiler", "licenses.html#gcc_web", null ],
      [ "3. Intel C++ compiler", "licenses.html#intel_web", null ]
    ] ],
    [ "Tools", "licenses.html#tools_web", [
      [ "1. Doxygen for design, theory, and software API documentation", "licenses.html#doxygen_web", null ],
      [ "2. CMake as a build system", "licenses.html#cmake_web", null ],
      [ "3. Ninja for building", "licenses.html#ninja_web", null ],
      [ "4. Gold for linking", "licenses.html#gold_web", null ],
      [ "5. Gcov for unit test coverage analysis", "licenses.html#gcov_web", null ],
      [ "6. Lcov for unit test coverage analysis report", "licenses.html#lcov_web", null ],
      [ "7. Git for source code version control", "licenses.html#git_web", null ],
      [ "8. Numdiff for comparison text files with numerical content", "licenses.html#numdiff_web", null ]
    ] ],
    [ "Charm++/Converse license", "_charm_license.html", null ],
    [ "PEGTL license", "_p_e_g_t_l_license.html", null ],
    [ "TUT license", "_t_u_t_license.html", null ],
    [ "Boost license", "_boost_license.html", null ],
    [ "Cartesian product license", "_cartesian__product_license.html", null ],
    [ "HDF5 license", "_h_d_f5_license.html", null ],
    [ "NetCDF license", "_net_c_d_f_license.html", null ],
    [ "ExodusII license", "_exodus_i_i_license.html", null ],
    [ "Zoltan license", "_zoltan_license.html", null ],
    [ "RNGSSELIB license", "_r_n_g_s_s_e_l_i_b_license.html", null ],
    [ "TestU01 license", "_test_u01_license.html", null ],
    [ "PStreams license", "_p_streams_license.html", null ],
    [ "Hypre license", "_hypre_license.html", null ],
    [ "LibStdC++ license", "_lib_std_c_p_p_license.html", null ],
    [ "LibC++ license", "_lib_c_p_p_license.html", null ],
    [ "OpenMPI license", "_open_m_p_i_license.html", null ],
    [ "MKL license", "_m_k_l_license.html", null ]
];