var licenses =
[
    [ "Third-party libraries", "licenses.html#tpl_licenses", [
      [ "1. The Charm++ Parallel Programming System", "licenses.html#charm_license", null ],
      [ "2. The Parsing Expression Grammar Template Library", "licenses.html#pegtl_license", null ],
      [ "3. C++ Template Unit Test Framework", "licenses.html#tut_license", null ],
      [ "4. Boost C++ libraries", "licenses.html#boost_license", null ],
      [ "5. Cartesian product, a Boost MPL algorithm", "licenses.html#cartesian_product_license", null ],
      [ "6. PStreams for POSIX process Control", "licenses.html#pstreams_license", null ],
      [ "7. The HDF5 data model", "licenses.html#hdf5_license", null ],
      [ "8. The NetCDF data model", "licenses.html#netcdf_license", null ],
      [ "9. ExodusII for storing data for finite element analyses", "licenses.html#exodusii_license", null ],
      [ "10. Zoltan for static load balancing", "licenses.html#zoltan_license", null ],
      [ "11. Hypre for linear solvers and preconditioners", "licenses.html#hypre_license", null ],
      [ "12. RNGSSELIB for random number generation", "licenses.html#rngsselib_license", null ],
      [ "13. TestU01 for statistical testing of random number generators", "licenses.html#testu01_license", null ],
      [ "14. PugiXML for XML format reading and writing", "licenses.html#pugixml_license", null ],
      [ "15. BLAS for basic linear algebra", "licenses.html#blas_license", null ],
      [ "16. LAPACK for linear algebra", "licenses.html#lapack_license", null ],
      [ "17. AEC for adaptive entropy coding", "licenses.html#aec_license", null ],
      [ "18. Libstdc++ for standard C++ containers and algorithms", "licenses.html#libstdcpp_license", null ],
      [ "19. Libc++ for standard C++ containers and algorithms", "licenses.html#libcpp_license", null ],
      [ "20. Musl-libc for standard C library", "licenses.html#musllibc_license", null ],
      [ "21. OpenMPI for the message passing interface", "licenses.html#openmpi_license", null ],
      [ "22. Intel Math Kernel Library for BLAS/LAPACK and random number generation", "licenses.html#mkl_license", null ]
    ] ],
    [ "Compilers", "licenses.html#compiler_web", [
      [ "1. Clang C++ compiler", "licenses.html#clang_web", null ],
      [ "2. GNU C++ compiler", "licenses.html#gcc_web", null ],
      [ "3. Intel C++ compiler", "licenses.html#intel_web", null ]
    ] ],
    [ "Tools", "licenses.html#tools_web", [
      [ "1. Doxygen for design, theory, and software API documentation", "licenses.html#doxygen_web", null ],
      [ "2. CMake as a build system", "licenses.html#cmake_web", null ],
      [ "3. Ninja for building", "licenses.html#ninja_web", null ],
      [ "4. Gold for linking", "licenses.html#gold_web", null ],
      [ "5. Gcov for unit test coverage analysis", "licenses.html#gcov_web", null ],
      [ "6. Lcov for unit test coverage analysis report", "licenses.html#lcov_web", null ],
      [ "7. Git for source code version control", "licenses.html#git_web", null ],
      [ "8. Numdiff for comparison text files with numerical content", "licenses.html#numdiff_web", null ]
    ] ],
    [ "Charm++/Converse license", "Charm_license.html", null ],
    [ "PEGTL license", "PEGTL_license.html", null ],
    [ "TUT license", "TUT_license.html", null ],
    [ "Boost license", "Boost_license.html", null ],
    [ "Cartesian product license", "Cartesian_Product_license.html", null ],
    [ "PStreams license", "PStreams_license.html", null ],
    [ "HDF5 license", "HDF5_license.html", null ],
    [ "NetCDF license", "NetCDF_license.html", null ],
    [ "ExodusII license", "ExodusII_license.html", null ],
    [ "Zoltan license", "Zoltan_license.html", null ],
    [ "Hypre license", "Hypre_license.html", null ],
    [ "RNGSSELIB license", "RNGSSELIB_license.html", null ],
    [ "TestU01 license", "TestU01_license.html", null ],
    [ "pugixml license", "PugiXML_license.html", null ],
    [ "BLAS license", "BLAS_license.html", null ],
    [ "LAPACK license", "LAPACK_license.html", null ],
    [ "AEC license", "AEC_license.html", null ],
    [ "LibStdC++ license", "LibStdCPP_license.html", null ],
    [ "LibC++ license", "LibCPP_license.html", null ],
    [ "Musllibc license", "Musllibc_license.html", null ],
    [ "OpenMPI license", "OpenMPI_license.html", null ],
    [ "MKL license", "MKL_license.html", null ]
];