var NAVTREEINDEX20 =
{
"walker_example_ou.html#walker_example_ou_output":[18,6,2],
"walker_example_ou.html#walker_example_ou_pdf":[18,6,4],
"walker_example_ou.html#walker_example_ou_run":[18,6,1],
"walker_example_skewnormal.html":[18,4],
"walker_example_skewnormal.html#walker_example_skewnormal_control":[18,4,0],
"walker_example_skewnormal.html#walker_example_skewnormal_output":[18,4,2],
"walker_example_skewnormal.html#walker_example_skewnormal_results":[18,4,3],
"walker_example_skewnormal.html#walker_example_skewnormal_run":[18,4,1],
"why.html":[17],
"why.html#correct":[17,1],
"why.html#documented":[17,7],
"why.html#exascale":[17,0],
"why.html#friendly":[17,6],
"why.html#fun":[17,8],
"why.html#language":[17,4],
"why.html#optimized":[17,2],
"why.html#outsource":[17,3],
"why.html#productivity":[17,5]
};
